# Generated by Django 5.2.17 on 2026-09-17 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimClass",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dim_class",
            },
        ),
        migrations.CreateModel(
            name="DimSubject",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "dim_subject",
            },
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                ("quarter", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "dim_time",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="running", max_length=24)),
                ("scope", models.JSONField()),
                ("cursor", models.JSONField(null=True)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("fetched", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("stale", models.PositiveIntegerField(default=0)),
                ("source_total", models.PositiveBigIntegerField(null=True)),
                ("source_total_relation", models.CharField(blank=True, max_length=8)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "extraction_run",
            },
        ),
        migrations.CreateModel(
            name="DimOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("court", models.CharField(max_length=16)),
                ("code", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("municipality_code", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "db_table": "dim_org",
                "constraints": [models.UniqueConstraint(fields=("court", "code"), name="unique_court_org")],
            },
        ),
        migrations.CreateModel(
            name="FactProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=255, unique=True)),
                ("number_process", models.CharField(max_length=32)),
                ("court", models.CharField(default="TJDFT", max_length=16)),
                ("degree", models.CharField(max_length=16)),
                ("secrecy_level", models.PositiveSmallIntegerField(default=0)),
                ("quant_process", models.PositiveSmallIntegerField(default=1)),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("source_timestamp", models.DateTimeField(null=True)),
                ("collected_at", models.DateTimeField(auto_now=True)),
                ("raw_payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "last_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="warehouse.extractionrun"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.dimorg"),
                ),
                (
                    "process_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.dimclass"),
                ),
                (
                    "time",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.dimtime"),
                ),
            ],
            options={
                "db_table": "fact_process",
            },
        ),
        migrations.CreateModel(
            name="FactProcessSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouse.factprocess"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.dimsubject"),
                ),
            ],
            options={
                "db_table": "fact_process_subject",
            },
        ),
        migrations.AddField(
            model_name="factprocess",
            name="subjects",
            field=models.ManyToManyField(through="warehouse.FactProcessSubject", to="warehouse.dimsubject"),
        ),
        migrations.CreateModel(
            name="ProcessMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("code", models.PositiveIntegerField(null=True)),
                ("name", models.CharField(max_length=512)),
                ("occurred_at", models.DateTimeField(null=True)),
                ("complements", models.JSONField(default=list)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="warehouse.factprocess",
                    ),
                ),
            ],
            options={
                "db_table": "process_movement",
            },
        ),
        migrations.CreateModel(
            name="RejectedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouse.extractionrun"
                    ),
                ),
            ],
            options={
                "db_table": "rejected_record",
            },
        ),
        migrations.AddConstraint(
            model_name="factprocesssubject",
            constraint=models.UniqueConstraint(fields=("process", "subject"), name="unique_process_subject"),
        ),
        migrations.AddIndex(
            model_name="factprocess",
            index=models.Index(fields=["court", "degree", "time"], name="fact_proces_court_77d263_idx"),
        ),
        migrations.AddConstraint(
            model_name="factprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("quant_process", 1)), name="process_weight_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="processmovement",
            constraint=models.UniqueConstraint(
                fields=("process", "fingerprint"), name="unique_process_movement"
            ),
        ),
    ]
