# Generated by Django 5.2.17 on 2026-09-23 01:49
# Intentional fresh-data transition: discards all warehouse v1 rows.
# Deploy to the separate datumlex_v2 database; see docs/resource-schema.md.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factprocess",
            name="subjects",
        ),
        migrations.DeleteModel(
            name="FactProcessSubject",
        ),
        migrations.DeleteModel(
            name="ProcessMovement",
        ),
        migrations.DeleteModel(
            name="RejectedRecord",
        ),
        migrations.DeleteModel(
            name="FactProcess",
        ),
        migrations.DeleteModel(
            name="ExtractionRun",
        ),
        migrations.DeleteModel(
            name="DimClass",
        ),
        migrations.DeleteModel(
            name="DimOrg",
        ),
        migrations.DeleteModel(
            name="DimSubject",
        ),
        migrations.DeleteModel(
            name="DimTime",
        ),
        migrations.CreateModel(
            name="DimClass",
            fields=[
                ("id", models.BigAutoField(db_column="id_class", primary_key=True, serialize=False)),
                ("code", models.PositiveIntegerField(db_column="code_class", unique=True)),
                ("name", models.CharField(db_column="name_class", max_length=100)),
            ],
            options={
                "db_table": "dim_class",
            },
        ),
        migrations.CreateModel(
            name="DimDegree",
            fields=[
                ("id", models.BigAutoField(db_column="id_degree", primary_key=True, serialize=False)),
                ("code", models.CharField(db_column="code_degree", max_length=50, unique=True)),
                ("name", models.CharField(db_column="name_degree", max_length=100)),
            ],
            options={
                "db_table": "dim_degree",
            },
        ),
        migrations.CreateModel(
            name="DimProcess",
            fields=[
                ("id", models.BigAutoField(db_column="id_process", primary_key=True, serialize=False)),
                ("number_process", models.CharField(max_length=20, unique=True)),
                ("secrecy_level", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "dim_process",
            },
        ),
        migrations.CreateModel(
            name="DimResult",
            fields=[
                ("id", models.BigAutoField(db_column="id_result", primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name_result", max_length=20, unique=True)),
            ],
            options={
                "db_table": "dim_result",
            },
        ),
        migrations.CreateModel(
            name="DimSubject",
            fields=[
                ("id", models.BigAutoField(db_column="id_subject", primary_key=True, serialize=False)),
                ("code", models.PositiveIntegerField(db_column="code_subject", unique=True)),
                ("name", models.CharField(db_column="name_subject", max_length=100)),
            ],
            options={
                "db_table": "dim_subject",
            },
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                ("id", models.BigAutoField(db_column="id_time", primary_key=True, serialize=False)),
                ("date", models.DateField(db_column="data", unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                ("quarter", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "dim_time",
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="running", max_length=24)),
                ("scope", models.JSONField()),
                ("cursor", models.JSONField(null=True)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("fetched", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("stale", models.PositiveIntegerField(default=0)),
                ("source_total", models.PositiveBigIntegerField(null=True)),
                ("source_total_relation", models.CharField(blank=True, max_length=8)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "extraction_run",
            },
        ),
        migrations.CreateModel(
            name="DimOrg",
            fields=[
                ("id", models.BigAutoField(db_column="id_org", primary_key=True, serialize=False)),
                ("court", models.CharField(max_length=16)),
                ("code", models.PositiveIntegerField(db_column="code_org")),
                ("name", models.CharField(db_column="name_org", max_length=100)),
                ("municipality_code", models.PositiveIntegerField(db_column="ibge_code", null=True)),
            ],
            options={
                "db_table": "dim_org",
                "constraints": [models.UniqueConstraint(fields=("court", "code"), name="unique_court_org")],
            },
        ),
        migrations.CreateModel(
            name="FactProcess",
            fields=[
                ("id", models.BigAutoField(db_column="id_resource", primary_key=True, serialize=False)),
                ("source_id", models.CharField(max_length=255, unique=True)),
                ("court", models.CharField(default="TJDFT", max_length=16)),
                ("quant_process", models.PositiveSmallIntegerField(db_column="quant_resource", default=1)),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("source_timestamp", models.DateTimeField(null=True)),
                ("collected_at", models.DateTimeField(auto_now=True)),
                ("raw_payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "degree_dimension",
                    models.ForeignKey(
                        db_column="id_degree",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdegree",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="warehouse.extractionrun"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="id_org", on_delete=django.db.models.deletion.PROTECT, to="warehouse.dimorg"
                    ),
                ),
                (
                    "process_class",
                    models.ForeignKey(
                        db_column="id_class",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimclass",
                    ),
                ),
                (
                    "process_dimension",
                    models.ForeignKey(
                        db_column="id_process",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimprocess",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        db_column="id_result",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimresult",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="id_time",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_resource",
            },
        ),
        migrations.CreateModel(
            name="FactProcessSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        db_column="id_resource",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.factprocess",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="id_subject",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimsubject",
                    ),
                ),
            ],
            options={
                "db_table": "fact_process_subject",
            },
        ),
        migrations.AddField(
            model_name="factprocess",
            name="subjects",
            field=models.ManyToManyField(through="warehouse.FactProcessSubject", to="warehouse.dimsubject"),
        ),
        migrations.CreateModel(
            name="ProcessMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("code", models.PositiveIntegerField(null=True)),
                ("name", models.CharField(max_length=512)),
                ("occurred_at", models.DateTimeField(null=True)),
                ("complements", models.JSONField(default=list)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="warehouse.factprocess",
                    ),
                ),
            ],
            options={
                "db_table": "process_movement",
            },
        ),
        migrations.CreateModel(
            name="RejectedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warehouse.extractionrun"
                    ),
                ),
            ],
            options={
                "db_table": "rejected_record",
            },
        ),
        migrations.AddConstraint(
            model_name="factprocesssubject",
            constraint=models.UniqueConstraint(fields=("process", "subject"), name="unique_process_subject"),
        ),
        migrations.AddIndex(
            model_name="factprocess",
            index=models.Index(
                fields=["court", "degree_dimension", "time"], name="fact_resour_court_eed40d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="factprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("quant_process", 1)), name="process_weight_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="processmovement",
            constraint=models.UniqueConstraint(
                fields=("process", "fingerprint"), name="unique_process_movement"
            ),
        ),
    ]
